### ISSUE TITLE
system restart on trade

### ISSUE THREAD

**Issue by samchin89** [nguyenviettuan96/mt5_AI_trading_bot#4]
everytime i restart python, it creates a new order, where do i adjust in the code (infer.py) to have a single trade only?

**Comment by nguyenviettuan96** [comment]
You consider position_type in this file and fix dict it to only long trade

**Comment by samchin89** [comment]
Nguyen, thanks for the guideline. One more, it opens trade every 4 hours, where should I alter to make the RL place 1 trade instead of it placing more orders every 4 hours?

**Comment by samchin89** [comment]
hi can i ask, if i start the code(infer.py), and it open a trade with an order id, and if i restart the code, will it remembers the last order id?

**Comment by nguyenviettuan96** [comment]
no it only knows these orders that were opened by code it
doesn't know previous order.

Vào Th 5, 19 thg 1, 2023 vào lúc 09:44 samchin89 ***@***.***>
đã viết:

**Comment by samchin89** [comment]
Nguyen, thanks for the clarification. The code from your repository is wonderful. Thanks for your contribution
