### ISSUE TITLE
Deviation

### ISSUE THREAD

**Issue by samchin89** [nguyenviettuan96/mt5_AI_trading_bot#5]
Hi Nguyen, how does the deviation affect the close order if I were to train it on 1H TF? Do I need to adjust it to higher or lower or it is fixed at 20 within the training and testing set?

**Comment by nguyenviettuan96** [comment]
You can adjust the deviation base on the volatility of the currency pair, if the asset is highly volatile, you may need to use a higher deviation value, whereas if the asset is less volatile, you may be able to use a lower deviation value. But remember that the deviation must be same on training and test set.
https://www.forex.com/en/market-analysis/latest-research/what-is-deviation-in-forex/

**Comment by samchin89** [comment]
Nguyen, thanks for the in-depth. Noted with thanks
